<a href="https://colab.research.google.com/github/kazutani2003/EU_M_Math/blob/main/Chap05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

練習問題5-1

In [10]:
import numpy as np
import random

sample_names = np.array(['a','b','c','d','a'])
np.random.seed(0)
data = np.random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]


In [12]:
data[sample_names == 'b']

array([[-0.97727788,  0.95008842, -0.15135721, -0.10321885,  0.4105985 ]])

練習問題5-2

In [14]:
import numpy as np
import random

sample_names = np.array(['a','b','c','d','a'])
np.random.seed(0)
data = np.random.randn(5,5)

print(sample_names)
print(data)

['a' 'b' 'c' 'd' 'a']
[[ 1.76405235  0.40015721  0.97873798  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.15135721 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.76103773  0.12167502  0.44386323]
 [ 0.33367433  1.49407907 -0.20515826  0.3130677  -0.85409574]
 [-2.55298982  0.6536186   0.8644362  -0.74216502  2.26975462]]


In [20]:
new_data = np.delete(sample_names, 2)
new_data = np.delete(data ,2 ,axis=1)
print(new_data)

[[ 1.76405235  0.40015721  2.2408932   1.86755799]
 [-0.97727788  0.95008842 -0.10321885  0.4105985 ]
 [ 0.14404357  1.45427351  0.12167502  0.44386323]
 [ 0.33367433  1.49407907  0.3130677  -0.85409574]
 [-2.55298982  0.6536186  -0.74216502  2.26975462]]


練習問題5-3

In [22]:
cond_data = np.array([False,False,True,True,False])

x_array= np.array([1,2,3,4,5])
y_array= np.array([6,7,8,9,10])

print(np.where(cond_data,x_array,y_array))

[ 6  7  3  4 10]
