<a href="https://colab.research.google.com/github/kazutani2003/EU_M_Math/blob/main/Chap05_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

5-3-1　例題

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(x**2/5.0)
plt.plot(x,y,'o')
plt.grid(True)
plt.show()

In [ ]:
from scipy import interpolate

f = interpolate.interp1d(x,y,'linear')
plt.plot(x,f(x),'-')
plt.grid(True)
plt.show()

In [ ]:
f2 = interpolate.interp1d(x,y,'cubic')
xnew = np.linspace(0, 10, num=30, endpoint=True)

plt.plot(x, y, 'o', xnew, f(xnew), '-', xnew, f2(xnew), '--')
plt.legend(['data', 'linear', 'cubic'],loc='best')
plt.grid(True)
plt.show()

練習問題5-10,5-11,5-12

In [ ]:
import numpy as np
from scipy import interpolate
import matplotlib.pyplot as plt
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(x**2/5.0)
f = interpolate.interp1d(x,y,'linear')
f2 = interpolate.interp1d(x,y,'cubic')
xnew = np.linspace(0,10,num=30,endpoint=True)

plt.plot(x,y,'o',xnew,f(xnew),'-',xnew,f2(xnew),'--')
plt.legend(['data','linear','cubic'],loc='best')
plt.grid(True)
plt.show()


5-3-2例題

In [ ]:
import numpy as np
import scipy as sp

A = np.array([[1,2,3,4,5],[6,7,8,9,10]])

U,s,Vs = sp.linalg.svd(A)
m,n = A.shape

S = sp.linalg.diagsvd(s,m,n)

print('U.S.V* = \n',U@S@Vs)

In [ ]:
import numpy as np
import scipy as sp
A = np.identity(5)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 5
b = np.ones(5)
(LU,piv) = sp.linalg.lu_factor(A)
x = sp.linalg.lu_solve((LU,piv),b)

print(x)


練習問題5-13

In [ ]:
import numpy as np
import scipy as sp
B = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

U,s,Vs = sp.linalg.svd(B)
m,n = B.shape

S = sp.linalg.diagsvd(s,m,n)

print('U.S.V* = \n',U@S@Vs)


練習問題 5-14

In [5]:
import numpy as np
import scipy as sp
A = np.identity(3)
print(A)
A[0,:] = 1
A[:,0] = 1
A[0,0] = 3
b = np.ones(3)
print(A)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[3. 1. 1.]
 [1. 1. 0.]
 [1. 0. 1.]]
[1. 1. 1.]
